name: Update semconv-latest branch (daily)

on:
  schedule:
    # daily at 10:24 UTC
    - cron: '24 10 * * *'
  workflow_dispatch:

jobs:
  update-semconv-latest-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # TODO (trask) may need to use OPENTELEMETRYBOT_GITHUB_TOKEN in order for PR workflows to get triggered
          ref: semconv-latest
          fetch-depth: 0 # this is needed in order to do rebase below

      - name: Use CLA approved github bot
        run: |
          git config user.name opentelemetrybot
          git config user.email 107717825+opentelemetrybot@users.noreply.github.com

      - name: Rebase
        run: |
          git fetch origin
          git rebase origin/main
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/semconv-latest)" ]; then
            git push origin semconv-latest
          fi

      - name: Update semconv submodule
        run: |
          git submodule update --init --remote content-modules/semantic-conventions
          if ! git diff-index --quiet HEAD; then
            git commit -am "Update semconv submodule"
            git push origin semconv-latest
          fi
