name: Update semconv-latest branch (daily)

on:
  schedule:
    # daily at 10:24 UTC
    - cron: '24 10 * * *'
  workflow_dispatch:

jobs:
  update-semconv-latest-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # TODO (trask) may need to use OPENTELEMETRYBOT_GITHUB_TOKEN in order for PR workflows to get triggered
          ref: semconv-latest

      - name: Use CLA approved github bot
        run: .github/workflows/scripts/use-cla-approved-github-bot.sh

      - name: Rebase
        run: |
          git fetch origin
          git rebase origin/main
          git push origin semconv-latest

      - name: Update semconv submodule
        run: |
          git submodule update --init --remote content-modules/semantic-conventions
          git commit -am "Update semconv submodule"
          git push origin semconv-latest
